### PR TITLE
Static CSV file generator

### PR DESCRIPTION
**Pull request by ats2008**
A starter script to make a csv.

Test  cmds
```
g++ src/make_testFile.cc -Iinclude/ -o csvMaker.exe
./csvMaker.exe -h
./csvMaker.exe -o test_csv.exe -n 128
head ./csvMaker.exe
```

TODO :
 * build system ( @debojitkumardas )

### CODE REVIEW

**Comment by debojitkumardas** [comment]
Create another branch for it. Let's keep the code for data generation separate.

**Comment by ats2008** [comment]
* Have made a change to base code to pick up names and other features randomly.
* Command line options added to specify customisation
* added features which are int and float
* Added possibility of having each raw to have a varying number of integer features
  * can be extended at some point to have flexibility in datatypes

**Comment by ats2008** [comment]
@debojitkumardas  , could you add a build system ? Makefile maybe ?

something like
```
make datagen
```
would make the `csvMaker.exe` ( checking if any of the dependencies have been updated )

**Comment by debojitkumardas** [comment]
Sure, I'll do it. Merging the PR.

**Pull request merged**
